branch-defaults:
  default:
    environment: udagram-api2-dev
deploy:
  artifact: www/Archive.zip
environment-defaults:
  udagram-api2-dev:
    branch: null
    repository: null
global:
  application_name: udagram-api2
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
